CREATE TABLE vehicles (
    plate_number VARCHAR(9) PRIMARY KEY,
    entry_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payments (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    plate_number VARCHAR(9) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    exit_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
